name: Android CI - build debug APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME_17: /opt/hostedtoolcache/jdk/17/x64

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable (if present)
      run: |
        if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

    - name: Generate gradle wrapper (if not present)
      run: |
        if [ ! -f ./gradlew ]; then sudo apt update && sudo apt install -y gradle; gradle wrapper --gradle-version 7.6 || true; fi

    - name: Build debug APK
      run: |
        if [ -f ./gradlew ]; then ./gradlew assembleDebug --no-daemon; else gradle assembleDebug --no-daemon; fi

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
