name: Android CI - build debug APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Gradle
      run: |
        sudo apt-get update
        sudo apt-get install -y gradle

    - name: Build debug APK with system Gradle
      run: |
        gradle assembleDebug --no-daemon

    - name: Upload debug APK (if produced)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
