name: Android CI - build debug APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Gradle 7.5
      run: |
        wget https://services.gradle.org/distributions/gradle-7.5-bin.zip -O gradle-7.5.zip
        unzip -q gradle-7.5.zip -d $HOME
        echo "$HOME/gradle-7.5/bin" >> $GITHUB_PATH

    - name: Show gradle version (debug)
      run: gradle --version

    - name: Build debug APK (use system Gradle)
      run: |
        # do NOT use ./gradlew even if present — use the Gradle we installed
        gradle assembleDebug --no-daemon

    - name: Upload debug APK (if produced)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
